### ISSUE TITLE
UIInterfaceOrientationMaskLandscapeLeft Not Supported

### ISSUE THREAD

**Issue by emcmanus** [pixo-vin/ios-sdk#2]
`videoview` is incorrectly mirrored when the device is in `UIInterfaceOrientationMaskLandscapeLeft`. `UIInterfaceOrientationMaskLandscapeRight` works as expected. It looks like SampleApplication has disabled `UIInterfaceOrientationMaskLandscapeLeft`.

Is there anything I need to do to support this orientation?

**Comment by pixovin** [comment]
Hi Ed,

Thanks for your reports! I wanted to confirm we received them and are
investigating further.

Warmly,

_Shawna Culp_

Pixo _|_ Executive Administrator
121 W. Goose Alley
Urbana, IL 61801
(217) 344-0444 x 17
http://pixotech.com/
_On the Job Consulting, Inc. DBA Pixo_
